--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categorie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorie (
    id integer NOT NULL,
    nom character varying(255) NOT NULL
);


ALTER TABLE public.categorie OWNER TO postgres;

--
-- Name: categorie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categorie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorie_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.categorie_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.categorie_seq OWNER TO postgres;

--
-- Name: commentaire; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.commentaire (
    id integer NOT NULL,
    description character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    echange_id integer NOT NULL
);


ALTER TABLE public.commentaire OWNER TO postgres;

--
-- Name: commentaire_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.commentaire ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commentaire_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commentaire_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.commentaire_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.commentaire_seq OWNER TO postgres;

--
-- Name: echange; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.echange (
    id integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    post_id integer NOT NULL,
    responder_id integer NOT NULL
);


ALTER TABLE public.echange OWNER TO postgres;

--
-- Name: echange_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.echange_detail (
    id integer NOT NULL,
    echange_id integer NOT NULL,
    objet_id integer NOT NULL
);


ALTER TABLE public.echange_detail OWNER TO postgres;

--
-- Name: echange_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.echange_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.echange_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: echange_detail_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.echange_detail_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.echange_detail_seq OWNER TO postgres;

--
-- Name: echange_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.echange ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.echange_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: echange_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.echange_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.echange_seq OWNER TO postgres;

--
-- Name: objet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.objet (
    id integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    nom character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    categorie_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.objet OWNER TO postgres;

--
-- Name: objet_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.objet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.objet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: objet_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.objet_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.objet_seq OWNER TO postgres;

--
-- Name: post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post (
    id integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    latitude double precision,
    longitude double precision,
    status boolean NOT NULL,
    titre character varying(255) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.post OWNER TO postgres;

--
-- Name: post_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post_detail (
    id integer NOT NULL,
    objet_id integer NOT NULL,
    post_id integer NOT NULL
);


ALTER TABLE public.post_detail OWNER TO postgres;

--
-- Name: post_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_detail_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.post_detail_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.post_detail_seq OWNER TO postgres;

--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.post_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.post_seq OWNER TO postgres;

--
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id integer NOT NULL,
    nom character varying(255) NOT NULL
);


ALTER TABLE public.role OWNER TO postgres;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.role_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.role_seq OWNER TO postgres;

--
-- Name: utilisateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utilisateur (
    id integer NOT NULL,
    birthday date,
    create_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    role_id integer
);


ALTER TABLE public.utilisateur OWNER TO postgres;

--
-- Name: utilisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utilisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateur_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.utilisateur_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.utilisateur_seq OWNER TO postgres;

--
-- Data for Name: categorie; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categorie (id, nom) FROM stdin;
\.


--
-- Data for Name: commentaire; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.commentaire (id, description, username, echange_id) FROM stdin;
\.


--
-- Data for Name: echange; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.echange (id, created_at, description, status, updated_at, post_id, responder_id) FROM stdin;
\.


--
-- Data for Name: echange_detail; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.echange_detail (id, echange_id, objet_id) FROM stdin;
\.


--
-- Data for Name: objet; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.objet (id, created_at, description, nom, updated_at, categorie_id, user_id) FROM stdin;
\.


--
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.post (id, created_at, description, latitude, longitude, status, titre, user_id) FROM stdin;
\.


--
-- Data for Name: post_detail; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.post_detail (id, objet_id, post_id) FROM stdin;
\.


--
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role (id, nom) FROM stdin;
1	USER
2	ADMIN
\.


--
-- Data for Name: utilisateur; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.utilisateur (id, birthday, create_at, email, password, username, role_id) FROM stdin;
1	1980-01-01	2024-07-18 09:10:22.784013	admin@example.com	$2a$12$JOtqzNRrgBeZVn5C62lQqOcTpnhHlkukZbJ.WDqpSwANJYyBYvaLm	admin_username	2
\.


--
-- Name: categorie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categorie_id_seq', 1, false);


--
-- Name: categorie_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categorie_seq', 1, false);


--
-- Name: commentaire_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.commentaire_id_seq', 1, false);


--
-- Name: commentaire_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.commentaire_seq', 1, false);


--
-- Name: echange_detail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.echange_detail_id_seq', 1, false);


--
-- Name: echange_detail_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.echange_detail_seq', 1, false);


--
-- Name: echange_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.echange_id_seq', 1, false);


--
-- Name: echange_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.echange_seq', 1, false);


--
-- Name: objet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.objet_id_seq', 1, false);


--
-- Name: objet_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.objet_seq', 1, false);


--
-- Name: post_detail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.post_detail_id_seq', 1, false);


--
-- Name: post_detail_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.post_detail_seq', 1, false);


--
-- Name: post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.post_id_seq', 1, false);


--
-- Name: post_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.post_seq', 1, false);


--
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_id_seq', 2, true);


--
-- Name: role_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_seq', 1, false);


--
-- Name: utilisateur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.utilisateur_id_seq', 1, true);


--
-- Name: utilisateur_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.utilisateur_seq', 1, false);


--
-- Name: categorie categorie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorie
    ADD CONSTRAINT categorie_pkey PRIMARY KEY (id);


--
-- Name: commentaire commentaire_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commentaire
    ADD CONSTRAINT commentaire_pkey PRIMARY KEY (id);


--
-- Name: echange_detail echange_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.echange_detail
    ADD CONSTRAINT echange_detail_pkey PRIMARY KEY (id);


--
-- Name: echange echange_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.echange
    ADD CONSTRAINT echange_pkey PRIMARY KEY (id);


--
-- Name: objet objet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.objet
    ADD CONSTRAINT objet_pkey PRIMARY KEY (id);


--
-- Name: post_detail post_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_detail
    ADD CONSTRAINT post_detail_pkey PRIMARY KEY (id);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: utilisateur ukrma38wvnqfaf66vvmi57c71lo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT ukrma38wvnqfaf66vvmi57c71lo UNIQUE (email);


--
-- Name: utilisateur utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT utilisateur_pkey PRIMARY KEY (id);


--
-- Name: post_detail fk46mm0e5earch2ws3ffhl533aa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_detail
    ADD CONSTRAINT fk46mm0e5earch2ws3ffhl533aa FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: post_detail fk6c0oogcsw35kd35wstvb8xlq2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_detail
    ADD CONSTRAINT fk6c0oogcsw35kd35wstvb8xlq2 FOREIGN KEY (objet_id) REFERENCES public.objet(id);


--
-- Name: objet fk6omvrec5rtiw14pms8dvnykar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.objet
    ADD CONSTRAINT fk6omvrec5rtiw14pms8dvnykar FOREIGN KEY (user_id) REFERENCES public.utilisateur(id);


--
-- Name: utilisateur fkaqe8xtajee4k0wlqrvh2pso4l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT fkaqe8xtajee4k0wlqrvh2pso4l FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: objet fkiy7ry5exsfraam972jbsvf7n7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.objet
    ADD CONSTRAINT fkiy7ry5exsfraam972jbsvf7n7 FOREIGN KEY (categorie_id) REFERENCES public.categorie(id);


--
-- Name: echange_detail fkj8y619xd49kgnig3p5bva802r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.echange_detail
    ADD CONSTRAINT fkj8y619xd49kgnig3p5bva802r FOREIGN KEY (objet_id) REFERENCES public.objet(id);


--
-- Name: echange fkkgkd1vmkq7eqgc9ss1tdr4dem; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.echange
    ADD CONSTRAINT fkkgkd1vmkq7eqgc9ss1tdr4dem FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: commentaire fkku7es7cbxdaro0pxhu8882n4i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commentaire
    ADD CONSTRAINT fkku7es7cbxdaro0pxhu8882n4i FOREIGN KEY (echange_id) REFERENCES public.echange(id);


--
-- Name: echange fkns18vtajesbh86snoa7vkbmwk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.echange
    ADD CONSTRAINT fkns18vtajesbh86snoa7vkbmwk FOREIGN KEY (responder_id) REFERENCES public.utilisateur(id);


--
-- Name: post fko8p2tlspw7vpi7fld3umifm7w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT fko8p2tlspw7vpi7fld3umifm7w FOREIGN KEY (user_id) REFERENCES public.utilisateur(id);


--
-- Name: echange_detail fkqr9yaos97toesamvrh50fw9gt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.echange_detail
    ADD CONSTRAINT fkqr9yaos97toesamvrh50fw9gt FOREIGN KEY (echange_id) REFERENCES public.echange(id);


--
-- PostgreSQL database dump complete
--

